# Test bed for loading database with SAdLSA data and visualizing the results

This notebook is a sandbox for loading SAdLSA data into the pandas dataframe, querying those dataframes, and then visualizing the alignment results.

### PREAMBLE

In [7]:
cd /home/rbdavid/Scripts/git/structural_DLFA/parsers

/home/rbdavid/Scripts/git/structural_DLFA/parsers

In [8]:
import sadlsa_parsers

In [9]:
cd /home/rbdavid/Scripts/git/structural_DLFA/visualizers

/home/rbdavid/Scripts/git/structural_DLFA/visualizers

In [10]:
import visualize_sadlsa_results
from pathlib import Path

### CHANGE THESE TO POINT TO YOUR OWN DATA FILES

In [11]:
data_dir = '/home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/'
working_dir = '/home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/'

In [12]:
mkdir /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/

mkdir: cannot create directory ‘/home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/’: File exists

### SANDBOX

In [13]:
score_file = data_dir + '/WP_164928147.1_sco.dat.gz'
alignment_file = data_dir + '/WP_164928147.1_aln.dat.gz'

In [14]:
score_df = sadlsa_parsers.parse_sadlsa_score_file(score_file)

In [15]:
score_df

,protein,seqname,alnlen,range1,tmscore1,range2,tmscore2,alnscore,seq_id
0,WP_164928147.1,5G3Q_A,49,3-51,0.3542,1-57,0.2628,473.20,18.4
1,WP_164928147.1,1DP3_A,44,8-51,0.3476,1-51,0.3418,503.39,15.9
2,WP_164928147.1,4QPO_A,44,8-51,0.3472,1-51,0.3445,503.61,20.5
3,WP_164928147.1,2D8U_A,51,1-51,0.3277,10-61,0.3168,575.45,11.8
4,WP_164928147.1,3OMY_B,45,7-51,0.3262,1-50,0.3254,511.72,13.3
5,WP_164928147.1,3OMY_A,45,7-51,0.3262,1-50,0.3254,511.72,13.3
6,WP_164928147.1,5Z7G_D,43,4-48,0.3175,1-43,0.3184,494.08,4.7
7,WP_164928147.1,5Z7L_D,43,4-48,0.3175,1-43,0.3184,494.08,4.7
8,WP_164928147.1,2KJF_A,50,1-51,0.3136,3-52,0.3014,529.80,8.0
9,WP_164928147.1,5U96_A,45,1-49,0.3124,8-52,0.3121,514.38,6.7

In [16]:
visualize_sadlsa_results.query_score_df(score_df)

array([['5G3Q_A', 0.3542, 473.2, 49, 18.4],
       ['1DP3_A', 0.3476, 503.39, 44, 15.9],
       ['4QPO_A', 0.3472, 503.61, 44, 20.5],
       ['2D8U_A', 0.3277, 575.45, 51, 11.8],
       ['3OMY_B', 0.3262, 511.72, 45, 13.3],
       ['3OMY_A', 0.3262, 511.72, 45, 13.3],
       ['5Z7G_D', 0.3175, 494.08, 43, 4.7],
       ['5Z7L_D', 0.3175, 494.08, 43, 4.7],
       ['2KJF_A', 0.3136, 529.8, 50, 8.0],
       ['5U96_A', 0.3124, 514.38, 45, 6.7]], dtype=object)

In [17]:
align_df = sadlsa_parsers.parse_sadlsa_aln_file(str(alignment_file),count=10)

In [18]:
align_df.head()

,protein,Aln_num,Prot_ID,naln,score,tms1,tms2,sid,Ind,Res1,AA1,Res2,AA2,MeanDist,Bin,Prob<3,Prob<5,Prob<8,S
0,WP_164928147.1,1,5G3Q_A,49,473.2,0.3542,0.2628,18.4,1,3,E,1,S,6.467,2,0.359,0.541,0.745,0
1,WP_164928147.1,1,5G3Q_A,49,473.2,0.3542,0.2628,18.4,2,4,D,2,M,5.247,2,0.479,0.657,0.828,0
2,WP_164928147.1,1,5G3Q_A,49,473.2,0.3542,0.2628,18.4,3,5,T,3,T,4.205,2,0.597,0.752,0.890,1
3,WP_164928147.1,1,5G3Q_A,49,473.2,0.3542,0.2628,18.4,4,6,R,4,S,3.416,1,0.705,0.831,0.929,0
4,WP_164928147.1,1,5G3Q_A,49,473.2,0.3542,0.2628,18.4,5,7,R,5,R,2.701,1,0.804,0.892,0.959,1

In [19]:
align_df.tail()

,protein,Aln_num,Prot_ID,naln,score,tms1,tms2,sid,Ind,Res1,AA1,Res2,AA2,MeanDist,Bin,Prob<3,Prob<5,Prob<8,S
454,WP_164928147.1,10,5U96_A,45,514.4,0.3124,0.3121,6.7,41,45,R,48,Q,2.853,1,0.825,0.871,0.927,0
455,WP_164928147.1,10,5U96_A,45,514.4,0.3124,0.3121,6.7,42,46,L,49,I,3.342,1,0.787,0.837,0.902,0
456,WP_164928147.1,10,5U96_A,45,514.4,0.3124,0.3121,6.7,43,47,T,50,E,3.754,1,0.750,0.810,0.882,0
457,WP_164928147.1,10,5U96_A,45,514.4,0.3124,0.3121,6.7,44,48,L,51,A,4.418,1,0.684,0.761,0.852,0
458,WP_164928147.1,10,5U96_A,45,514.4,0.3124,0.3121,6.7,45,49,G,52,N,5.347,2,0.576,0.691,0.812,0

In [20]:
visualize_sadlsa_results.query_alignment_df(align_df,'5G3Q_A','Prob<3')

array([[ 1.   ,  0.359],
       [ 2.   ,  0.479],
       [ 3.   ,  0.597],
       [ 4.   ,  0.705],
       [ 5.   ,  0.804],
       [ 6.   ,  0.867],
       [ 7.   ,  0.916],
       [ 8.   ,  0.938],
       [ 9.   ,  0.941],
       [10.   ,  0.945],
       [11.   ,  0.94 ],
       [12.   ,  0.93 ],
       [13.   ,  0.919],
       [14.   ,  0.877],
       [15.   ,  0.807],
       [16.   ,  0.757],
       [17.   ,  0.75 ],
       [18.   ,  0.78 ],
       [19.   ,  0.808],
       [20.   ,  0.81 ],
       [21.   ,  0.804],
       [22.   ,  0.807],
       [23.   ,  0.801],
       [24.   ,  0.754],
       [25.   ,  0.71 ],
       [26.   ,  0.636],
       [27.   ,  0.532],
       [28.   ,  0.422],
       [29.   ,  0.339],
       [30.   ,  0.281],
       [31.   ,  0.248],
       [32.   ,  0.236],
       [33.   ,  0.234],
       [34.   ,  0.233],
       [35.   ,  0.215],
       [36.   ,  0.228],
       [37.   ,  0.221],
       [38.   ,  0.201],
       [47.   ,  0.242],
       [48.   ,  0.233],
       [49.   ,  0.23 ],
       [50.   ,  0.209],
       [51.   ,  0.18 ],
       [52.   ,  0.161],
       [53.   ,  0.152],
       [54.   ,  0.113],
       [55.   ,  0.09 ],
       [56.   ,  0.076],
       [57.   ,  0.065]])

In [21]:
for pdb in visualize_sadlsa_results.query_score_df(score_df)[:,0]:
    pdbid = pdb[:-2]
    temp = visualize_sadlsa_results.query_alignment_df(align_df, pdb,"Prob<3")
    visualize_sadlsa_results.grab_structure(pdb[:-2],working_dir=working_dir)
    visualize_sadlsa_results.edit_pdb(working_dir+'%s.pdb'%(pdb[:-2]),pdb[-1],temp,"Prob<3")
    visualize_sadlsa_results.create_vmd_vis_state(working_dir+'%s_Prob<3.vmd'%(pdb),
                     working_dir+'%s_Prob<3_colorbar.png'%(pdb),
                     working_dir+'%s_Prob<3.pdb'%(pdb),1.0,'blue',colorbar_label='Prob < 3 $\AA$')

Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5G3Q_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5G3Q_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/1DP3_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/1DP3_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/4QPO_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/4QPO_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/2D8U_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/2D8U_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/3OMY_B_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/3OMY_B_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/3OMY_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/3OMY_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5Z7G_D_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5Z7G_D_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5Z7L_D_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5Z7L_D_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/2KJF_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/2KJF_A_Prob<3_colorbar.png
Finished creating vis-state file /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5U96_A_Prob<3.vmd
Finished creating colorbar figure /home/rbdavid/Projects/ornl_DLFA/temp_sadlsa_results/temp/5U96_A_Prob<3_colorbar.png